out_dir: results
metric_best: f1
wandb:
  use: False
dataset:
  format: PyG-SocialNetwork
  name: none
  task: node
  task_type: classification
  transductive: True
  split_mode: standard
  node_encoder: True
  node_encoder_name: LinearNode
  node_encoder_bn: False
  edge_encoder: False
train:
  mode: custom
  sampler: full_batch
  eval_period: 1
  enable_ckpt: False
model:
  type: GPSModel
  loss_fun: weighted_cross_entropy
gt:
  layer_type: GCN+Performer
  layers: 2
  n_heads: 4
  dim_hidden: 64
  dropout: 0.2
  attn_dropout: 0.0
  layer_norm: False
  batch_norm: False
gnn:
  head: node
  layers_pre_mp: 0
  layers_post_mp: 1
  dim_inner: 64
  batchnorm: True
  act: gelu
  dropout: 0.2
  agg: mean
  normalize_adj: False
optim:
  clip_grad_norm: True
  optimizer: adamW
  weight_decay: 1e-5
  base_lr: 0.0005
  max_epoch: 1000
  scheduler: cosine_with_warmup
  num_warmup_epochs: 50
accelerator: cuda
